name: Deploy to Production

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create pull request for review
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout -b staging-to-production
        git add .
        git commit -m "Merge staging into production"
        git push origin staging-to-production

    - name: Wait for pull request approval
      uses: wei/pull-request-approve-action@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge changes into production
      run: |
        git fetch origin
        git checkout production
        git merge --no-ff staging-to-production -m "Merge pull request #${{ github.event.pull_request.number }} from staging into production"
        git push origin production

    - name: Clean up
      run: |
        git checkout staging
        git branch -D staging-to-production
