name: cicd

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
    


            
  DeployProd:
    name: Deploy to Production 
    
    runs-on: ubuntu-latest
    environment: 
      name: Production 
    steps:
      - name: Deploy
        run: echo I am deploying! 
    
