name: cicd

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
    

            
  DeployProd:
    name: Deploy to Production 
    runs-on: ubuntu-latest
    environment: 
      name: Production 
    steps:
      - name: Install Python 3.6.15
        run: |
          mkdir -p ~/python
          cd ~/python
          wget https://github.com/actions/python-versions/releases/download/3.6.15-116025/python-3.6.15-linux-20.04-x64.tar.gz
          tar xzf python-3.6.15-linux-20.04-x64.tar.gz
          export PATH="$HOME/python/bin:$PATH"
          python --version  # Verify Python installation
      - name: Install databricks cli
        run: |
          python -m pip install --upgrade databricks-cli
      - name: Remote update Prod Repo
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks repos update --branch production --path /Repos/shaswat@onebyzero/databricks_production
      - name: Updating branch
        run: |
          cd /Shaswat19/databricks_staging
          git checkout production  # Switch to production branch
          git pull origin staging  # Pull latest changes from staging branch
          git push origin production  # Push changes to production branch
