name: Merge to Production

on:
  push:
    branches:
      - staging
jobs:
  merge_to_production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: production
          base: production
          title: 'Merge changes from staging to production'
          body: 'Please review and approve the changes.'

      - name: Wait for Approval
        if: steps.create_pr.outputs.pull-request-number
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${ { steps.create_pr.outputs.pull-request-number } }
            });
            const approvals = response.data.filter(review => review.state === 'APPROVED');
            if (approvals.length >= 1) {
              console.log('PR approved. Merging changes to production.');
              await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: ${ { steps.create_pr.outputs.pull-request-number } }
              });
            } else {
              console.log('PR is not yet approved.');
            }
